from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

main = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'2EDGK_5_08_2P_12V_INPUT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2EDGK_5_08_2P_12V_INPUT'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'EasyEDA:2EDGK_5_08_2P_12V_INPUT', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'S1206_F_2A_INPUT_FUSE', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'S1206_F_2A_INPUT_FUSE'}), 'ref_prefix':'F', 'fplist':None, 'footprint':'EasyEDA:S1206_F_2A_INPUT_FUSE', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'SS34_INPUT_REVERSE_PROTECTION', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SS34_INPUT_REVERSE_PROTECTION'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'EasyEDA:SS34_INPUT_REVERSE_PROTECTION', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.UNSPEC),
            Pin(num='2',name='A',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'SMAJ18A_INPUT_TVS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SMAJ18A_INPUT_TVS'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'EasyEDA:SMAJ18A_INPUT_TVS', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='K',func=pin_types.UNSPEC),
            Pin(num='2',name='A',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'AP63203WU_7_3V3_BUCK', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP63203WU_7_3V3_BUCK'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'EasyEDA:AP63203WU_7_3V3_BUCK', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='VIN',func=pin_types.UNSPEC),
            Pin(num='2',name='GND',func=pin_types.UNSPEC),
            Pin(num='3',name='EN',func=pin_types.UNSPEC),
            Pin(num='4',name='BST',func=pin_types.UNSPEC),
            Pin(num='5',name='SW',func=pin_types.UNSPEC),
            Pin(num='6',name='FB',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LOGIC_BUCK_INDUCTOR_4U7_3A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LOGIC_BUCK_INDUCTOR_4U7_3A'}), 'ref_prefix':'L', 'fplist':None, 'footprint':'EasyEDA:LOGIC_BUCK_INDUCTOR_4U7_3A', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LOGIC_BUCK_INPUT_10UF_25V', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LOGIC_BUCK_INPUT_10UF_25V'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:LOGIC_BUCK_INPUT_10UF_25V', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LOGIC_BUCK_OUTPUT_22UF_25V_A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LOGIC_BUCK_OUTPUT_22UF_25V_A'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:LOGIC_BUCK_OUTPUT_22UF_25V_A', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LOGIC_BUCK_OUTPUT_22UF_25V_B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LOGIC_BUCK_OUTPUT_22UF_25V_B'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:LOGIC_BUCK_OUTPUT_22UF_25V_B', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LOGIC_BUCK_BOOTSTRAP_100NF', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LOGIC_BUCK_BOOTSTRAP_100NF'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:LOGIC_BUCK_BOOTSTRAP_100NF', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'STM32F429IGT6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32F429IGT6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'EasyEDA:STM32F429IGT6', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='VDD',name='VDD',func=pin_types.UNSPEC),
            Pin(num='VSS',name='VSS',func=pin_types.UNSPEC),
            Pin(num='VDDA',name='VDDA',func=pin_types.UNSPEC),
            Pin(num='VSSA',name='VSSA',func=pin_types.UNSPEC),
            Pin(num='NRST',name='NRST',func=pin_types.UNSPEC),
            Pin(num='BOOT0',name='BOOT0',func=pin_types.UNSPEC),
            Pin(num='OSC_IN',name='PH0_OSC_IN',func=pin_types.UNSPEC),
            Pin(num='OSC_OUT',name='PH1_OSC_OUT',func=pin_types.UNSPEC),
            Pin(num='USB_DM',name='PA11_USB_DM',func=pin_types.UNSPEC),
            Pin(num='USB_DP',name='PA12_USB_DP',func=pin_types.UNSPEC),
            Pin(num='SWDIO',name='PA13_SWDIO',func=pin_types.UNSPEC),
            Pin(num='SWCLK',name='PA14_SWCLK',func=pin_types.UNSPEC),
            Pin(num='SWO',name='PB3_SWO',func=pin_types.UNSPEC),
            Pin(num='I2C1_SCL',name='PB8_I2C1_SCL',func=pin_types.UNSPEC),
            Pin(num='I2C1_SDA',name='PB9_I2C1_SDA',func=pin_types.UNSPEC),
            Pin(num='TOUCH_IRQ',name='PB7_TOUCH_IRQ',func=pin_types.UNSPEC),
            Pin(num='LCD_BL_PWM',name='PA8_LCD_BL_PWM',func=pin_types.UNSPEC),
            Pin(num='SD_CARD_DETECT',name='PG3_SD_CARD_DETECT',func=pin_types.UNSPEC),
            Pin(num='SDIO_D0',name='PC8_SDIO_D0',func=pin_types.UNSPEC),
            Pin(num='SDIO_D1',name='PC9_SDIO_D1',func=pin_types.UNSPEC),
            Pin(num='SDIO_D2',name='PC10_SDIO_D2',func=pin_types.UNSPEC),
            Pin(num='SDIO_D3',name='PC11_SDIO_D3',func=pin_types.UNSPEC),
            Pin(num='SDIO_CK',name='PC12_SDIO_CK',func=pin_types.UNSPEC),
            Pin(num='SDIO_CMD',name='PD2_SDIO_CMD',func=pin_types.UNSPEC),
            Pin(num='LCD_CLK',name='PI14_LCD_CLK',func=pin_types.UNSPEC),
            Pin(num='LCD_DE',name='PK7_LCD_DE',func=pin_types.UNSPEC),
            Pin(num='LCD_HSYNC',name='PI10_LCD_HSYNC',func=pin_types.UNSPEC),
            Pin(num='LCD_VSYNC',name='PI9_LCD_VSYNC',func=pin_types.UNSPEC),
            Pin(num='LCD_R0',name='PI15_LCD_R0',func=pin_types.UNSPEC),
            Pin(num='LCD_R1',name='PJ0_LCD_R1',func=pin_types.UNSPEC),
            Pin(num='LCD_R2',name='PJ1_LCD_R2',func=pin_types.UNSPEC),
            Pin(num='LCD_R3',name='PJ2_LCD_R3',func=pin_types.UNSPEC),
            Pin(num='LCD_R4',name='PJ3_LCD_R4',func=pin_types.UNSPEC),
            Pin(num='LCD_R5',name='PJ4_LCD_R5',func=pin_types.UNSPEC),
            Pin(num='LCD_R6',name='PJ5_LCD_R6',func=pin_types.UNSPEC),
            Pin(num='LCD_R7',name='PJ6_LCD_R7',func=pin_types.UNSPEC),
            Pin(num='LCD_G0',name='PJ7_LCD_G0',func=pin_types.UNSPEC),
            Pin(num='LCD_G1',name='PJ8_LCD_G1',func=pin_types.UNSPEC),
            Pin(num='LCD_G2',name='PJ9_LCD_G2',func=pin_types.UNSPEC),
            Pin(num='LCD_G3',name='PJ10_LCD_G3',func=pin_types.UNSPEC),
            Pin(num='LCD_G4',name='PJ11_LCD_G4',func=pin_types.UNSPEC),
            Pin(num='LCD_G5',name='PK0_LCD_G5',func=pin_types.UNSPEC),
            Pin(num='LCD_G6',name='PK1_LCD_G6',func=pin_types.UNSPEC),
            Pin(num='LCD_G7',name='PK2_LCD_G7',func=pin_types.UNSPEC),
            Pin(num='LCD_B0',name='PJ12_LCD_B0',func=pin_types.UNSPEC),
            Pin(num='LCD_B1',name='PJ13_LCD_B1',func=pin_types.UNSPEC),
            Pin(num='LCD_B2',name='PJ14_LCD_B2',func=pin_types.UNSPEC),
            Pin(num='LCD_B3',name='PJ15_LCD_B3',func=pin_types.UNSPEC),
            Pin(num='LCD_B4',name='PK3_LCD_B4',func=pin_types.UNSPEC),
            Pin(num='LCD_B5',name='PI5_LCD_B5',func=pin_types.UNSPEC),
            Pin(num='LCD_B6',name='PI6_LCD_B6',func=pin_types.UNSPEC),
            Pin(num='LCD_B7',name='PI7_LCD_B7',func=pin_types.UNSPEC),
            Pin(num='FMC_D0',name='PD14_FMC_D0',func=pin_types.UNSPEC),
            Pin(num='FMC_D1',name='PD15_FMC_D1',func=pin_types.UNSPEC),
            Pin(num='FMC_D2',name='PD0_FMC_D2',func=pin_types.UNSPEC),
            Pin(num='FMC_D3',name='PD1_FMC_D3',func=pin_types.UNSPEC),
            Pin(num='FMC_D4',name='PE7_FMC_D4',func=pin_types.UNSPEC),
            Pin(num='FMC_D5',name='PE8_FMC_D5',func=pin_types.UNSPEC),
            Pin(num='FMC_D6',name='PE9_FMC_D6',func=pin_types.UNSPEC),
            Pin(num='FMC_D7',name='PE10_FMC_D7',func=pin_types.UNSPEC),
            Pin(num='FMC_D8',name='PE11_FMC_D8',func=pin_types.UNSPEC),
            Pin(num='FMC_D9',name='PE12_FMC_D9',func=pin_types.UNSPEC),
            Pin(num='FMC_D10',name='PE13_FMC_D10',func=pin_types.UNSPEC),
            Pin(num='FMC_D11',name='PE14_FMC_D11',func=pin_types.UNSPEC),
            Pin(num='FMC_D12',name='PE15_FMC_D12',func=pin_types.UNSPEC),
            Pin(num='FMC_D13',name='PD8_FMC_D13',func=pin_types.UNSPEC),
            Pin(num='FMC_D14',name='PD9_FMC_D14',func=pin_types.UNSPEC),
            Pin(num='FMC_D15',name='PD10_FMC_D15',func=pin_types.UNSPEC),
            Pin(num='FMC_A0',name='PF0_FMC_A0',func=pin_types.UNSPEC),
            Pin(num='FMC_A1',name='PF1_FMC_A1',func=pin_types.UNSPEC),
            Pin(num='FMC_A2',name='PF2_FMC_A2',func=pin_types.UNSPEC),
            Pin(num='FMC_A3',name='PF3_FMC_A3',func=pin_types.UNSPEC),
            Pin(num='FMC_A4',name='PF4_FMC_A4',func=pin_types.UNSPEC),
            Pin(num='FMC_A5',name='PF5_FMC_A5',func=pin_types.UNSPEC),
            Pin(num='FMC_A6',name='PF12_FMC_A6',func=pin_types.UNSPEC),
            Pin(num='FMC_A7',name='PF13_FMC_A7',func=pin_types.UNSPEC),
            Pin(num='FMC_A8',name='PF14_FMC_A8',func=pin_types.UNSPEC),
            Pin(num='FMC_A9',name='PF15_FMC_A9',func=pin_types.UNSPEC),
            Pin(num='FMC_A10',name='PG0_FMC_A10',func=pin_types.UNSPEC),
            Pin(num='FMC_A11',name='PG1_FMC_A11',func=pin_types.UNSPEC),
            Pin(num='FMC_A12',name='PG2_FMC_A12',func=pin_types.UNSPEC),
            Pin(num='FMC_BA0',name='PG4_FMC_BA0',func=pin_types.UNSPEC),
            Pin(num='FMC_BA1',name='PG5_FMC_BA1',func=pin_types.UNSPEC),
            Pin(num='FMC_SDCLK',name='PG8_FMC_SDCLK',func=pin_types.UNSPEC),
            Pin(num='FMC_SDCKE1',name='PB5_FMC_SDCKE1',func=pin_types.UNSPEC),
            Pin(num='FMC_SDNE1',name='PB6_FMC_SDNE1',func=pin_types.UNSPEC),
            Pin(num='FMC_SDNRAS',name='PF11_FMC_SDNRAS',func=pin_types.UNSPEC),
            Pin(num='FMC_SDNCAS',name='PG15_FMC_SDNCAS',func=pin_types.UNSPEC),
            Pin(num='FMC_SDNWE',name='PC0_FMC_SDNWE',func=pin_types.UNSPEC),
            Pin(num='FMC_NBL0',name='PE0_FMC_NBL0',func=pin_types.UNSPEC),
            Pin(num='FMC_NBL1',name='PE1_FMC_NBL1',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'W9825G6JH_6_SDRAM', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'W9825G6JH_6_SDRAM'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'EasyEDA:W9825G6JH_6_SDRAM', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='VDD',name='VDD',func=pin_types.UNSPEC),
            Pin(num='VDDQ',name='VDDQ',func=pin_types.UNSPEC),
            Pin(num='VSS',name='VSS',func=pin_types.UNSPEC),
            Pin(num='VSSQ',name='VSSQ',func=pin_types.UNSPEC),
            Pin(num='DQ0',name='DQ0',func=pin_types.UNSPEC),
            Pin(num='DQ1',name='DQ1',func=pin_types.UNSPEC),
            Pin(num='DQ2',name='DQ2',func=pin_types.UNSPEC),
            Pin(num='DQ3',name='DQ3',func=pin_types.UNSPEC),
            Pin(num='DQ4',name='DQ4',func=pin_types.UNSPEC),
            Pin(num='DQ5',name='DQ5',func=pin_types.UNSPEC),
            Pin(num='DQ6',name='DQ6',func=pin_types.UNSPEC),
            Pin(num='DQ7',name='DQ7',func=pin_types.UNSPEC),
            Pin(num='DQ8',name='DQ8',func=pin_types.UNSPEC),
            Pin(num='DQ9',name='DQ9',func=pin_types.UNSPEC),
            Pin(num='DQ10',name='DQ10',func=pin_types.UNSPEC),
            Pin(num='DQ11',name='DQ11',func=pin_types.UNSPEC),
            Pin(num='DQ12',name='DQ12',func=pin_types.UNSPEC),
            Pin(num='DQ13',name='DQ13',func=pin_types.UNSPEC),
            Pin(num='DQ14',name='DQ14',func=pin_types.UNSPEC),
            Pin(num='DQ15',name='DQ15',func=pin_types.UNSPEC),
            Pin(num='A0',name='A0',func=pin_types.UNSPEC),
            Pin(num='A1',name='A1',func=pin_types.UNSPEC),
            Pin(num='A2',name='A2',func=pin_types.UNSPEC),
            Pin(num='A3',name='A3',func=pin_types.UNSPEC),
            Pin(num='A4',name='A4',func=pin_types.UNSPEC),
            Pin(num='A5',name='A5',func=pin_types.UNSPEC),
            Pin(num='A6',name='A6',func=pin_types.UNSPEC),
            Pin(num='A7',name='A7',func=pin_types.UNSPEC),
            Pin(num='A8',name='A8',func=pin_types.UNSPEC),
            Pin(num='A9',name='A9',func=pin_types.UNSPEC),
            Pin(num='A10',name='A10',func=pin_types.UNSPEC),
            Pin(num='A11',name='A11',func=pin_types.UNSPEC),
            Pin(num='A12',name='A12',func=pin_types.UNSPEC),
            Pin(num='BA0',name='BA0',func=pin_types.UNSPEC),
            Pin(num='BA1',name='BA1',func=pin_types.UNSPEC),
            Pin(num='CLK',name='CLK',func=pin_types.UNSPEC),
            Pin(num='CKE',name='CKE',func=pin_types.UNSPEC),
            Pin(num='CS_N',name='CS_N',func=pin_types.UNSPEC),
            Pin(num='RAS_N',name='RAS_N',func=pin_types.UNSPEC),
            Pin(num='CAS_N',name='CAS_N',func=pin_types.UNSPEC),
            Pin(num='WE_N',name='WE_N',func=pin_types.UNSPEC),
            Pin(num='LDQM',name='LDQM',func=pin_types.UNSPEC),
            Pin(num='UDQM',name='UDQM',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'DWIN_LN80480T070IA9098_LCD_50P_FPC', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DWIN_LN80480T070IA9098_LCD_50P_FPC'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'EasyEDA:DWIN_LN80480T070IA9098_LCD_50P_FPC', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC),
            Pin(num='5',name='5',func=pin_types.UNSPEC),
            Pin(num='6',name='6',func=pin_types.UNSPEC),
            Pin(num='7',name='7',func=pin_types.UNSPEC),
            Pin(num='8',name='8',func=pin_types.UNSPEC),
            Pin(num='9',name='9',func=pin_types.UNSPEC),
            Pin(num='10',name='10',func=pin_types.UNSPEC),
            Pin(num='11',name='11',func=pin_types.UNSPEC),
            Pin(num='12',name='12',func=pin_types.UNSPEC),
            Pin(num='13',name='13',func=pin_types.UNSPEC),
            Pin(num='14',name='14',func=pin_types.UNSPEC),
            Pin(num='15',name='15',func=pin_types.UNSPEC),
            Pin(num='16',name='16',func=pin_types.UNSPEC),
            Pin(num='17',name='17',func=pin_types.UNSPEC),
            Pin(num='18',name='18',func=pin_types.UNSPEC),
            Pin(num='19',name='19',func=pin_types.UNSPEC),
            Pin(num='20',name='20',func=pin_types.UNSPEC),
            Pin(num='21',name='21',func=pin_types.UNSPEC),
            Pin(num='22',name='22',func=pin_types.UNSPEC),
            Pin(num='23',name='23',func=pin_types.UNSPEC),
            Pin(num='24',name='24',func=pin_types.UNSPEC),
            Pin(num='25',name='25',func=pin_types.UNSPEC),
            Pin(num='26',name='26',func=pin_types.UNSPEC),
            Pin(num='27',name='27',func=pin_types.UNSPEC),
            Pin(num='28',name='28',func=pin_types.UNSPEC),
            Pin(num='29',name='29',func=pin_types.UNSPEC),
            Pin(num='30',name='30',func=pin_types.UNSPEC),
            Pin(num='31',name='31',func=pin_types.UNSPEC),
            Pin(num='32',name='32',func=pin_types.UNSPEC),
            Pin(num='33',name='33',func=pin_types.UNSPEC),
            Pin(num='34',name='34',func=pin_types.UNSPEC),
            Pin(num='35',name='35',func=pin_types.UNSPEC),
            Pin(num='36',name='36',func=pin_types.UNSPEC),
            Pin(num='37',name='37',func=pin_types.UNSPEC),
            Pin(num='38',name='38',func=pin_types.UNSPEC),
            Pin(num='39',name='39',func=pin_types.UNSPEC),
            Pin(num='40',name='40',func=pin_types.UNSPEC),
            Pin(num='41',name='41',func=pin_types.UNSPEC),
            Pin(num='42',name='42',func=pin_types.UNSPEC),
            Pin(num='43',name='43',func=pin_types.UNSPEC),
            Pin(num='44',name='44',func=pin_types.UNSPEC),
            Pin(num='45',name='45',func=pin_types.UNSPEC),
            Pin(num='46',name='46',func=pin_types.UNSPEC),
            Pin(num='47',name='47',func=pin_types.UNSPEC),
            Pin(num='48',name='48',func=pin_types.UNSPEC),
            Pin(num='49',name='49',func=pin_types.UNSPEC),
            Pin(num='50',name='50',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LCD_BIAS_POWER_PORT_REVIEW', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LCD_BIAS_POWER_PORT_REVIEW'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'EasyEDA:LCD_BIAS_POWER_PORT_REVIEW', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='VIN',name='VIN',func=pin_types.UNSPEC),
            Pin(num='GND',name='GND',func=pin_types.UNSPEC),
            Pin(num='AVDD',name='AVDD',func=pin_types.UNSPEC),
            Pin(num='VGH',name='VGH',func=pin_types.UNSPEC),
            Pin(num='VGL',name='VGL',func=pin_types.UNSPEC),
            Pin(num='VCOM',name='VCOM',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LCD_MODE_PULLDOWN_10K', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LCD_MODE_PULLDOWN_10K'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'EasyEDA:LCD_MODE_PULLDOWN_10K', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LCD_UD_PULLDOWN_10K', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LCD_UD_PULLDOWN_10K'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'EasyEDA:LCD_UD_PULLDOWN_10K', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LCD_BACKLIGHT_DRIVER_REVIEW', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LCD_BACKLIGHT_DRIVER_REVIEW'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'EasyEDA:LCD_BACKLIGHT_DRIVER_REVIEW', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='VIN',name='VIN',func=pin_types.UNSPEC),
            Pin(num='GND',name='GND',func=pin_types.UNSPEC),
            Pin(num='LEDA',name='LEDA',func=pin_types.UNSPEC),
            Pin(num='LEDK',name='LEDK',func=pin_types.UNSPEC),
            Pin(num='PWM',name='PWM',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'YF07002_TOUCH_4P_FPC', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'YF07002_TOUCH_4P_FPC'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'EasyEDA:YF07002_TOUCH_4P_FPC', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'AR1020_I_SS_TOUCH_CONTROLLER', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AR1020_I_SS_TOUCH_CONTROLLER'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'EasyEDA:AR1020_I_SS_TOUCH_CONTROLLER', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='VDD',name='VDD',func=pin_types.UNSPEC),
            Pin(num='VSS',name='VSS',func=pin_types.UNSPEC),
            Pin(num='M1',name='M1',func=pin_types.UNSPEC),
            Pin(num='M2',name='M2',func=pin_types.UNSPEC),
            Pin(num='WAKE',name='WAKE',func=pin_types.UNSPEC),
            Pin(num='IRQ',name='SIQ_IRQ',func=pin_types.UNSPEC),
            Pin(num='SDA',name='SDI_SDA_RX',func=pin_types.UNSPEC),
            Pin(num='SCL',name='SCK_SCL_TX',func=pin_types.UNSPEC),
            Pin(num='XPLUS',name='XPLUS',func=pin_types.UNSPEC),
            Pin(num='XMINUS',name='XMINUS',func=pin_types.UNSPEC),
            Pin(num='YPLUS',name='YPLUS',func=pin_types.UNSPEC),
            Pin(num='YMINUS',name='YMINUS',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'I2C_SCL_PULLUP_4K7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'I2C_SCL_PULLUP_4K7'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'EasyEDA:I2C_SCL_PULLUP_4K7', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'I2C_SDA_PULLUP_4K7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'I2C_SDA_PULLUP_4K7'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'EasyEDA:I2C_SDA_PULLUP_4K7', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'MICROSD_SOCKET_HYC39_TF08_180', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MICROSD_SOCKET_HYC39_TF08_180'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'EasyEDA:MICROSD_SOCKET_HYC39_TF08_180', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='DAT0',name='DAT0',func=pin_types.UNSPEC),
            Pin(num='DAT1',name='DAT1',func=pin_types.UNSPEC),
            Pin(num='DAT2',name='DAT2',func=pin_types.UNSPEC),
            Pin(num='DAT3',name='DAT3',func=pin_types.UNSPEC),
            Pin(num='CLK',name='CLK',func=pin_types.UNSPEC),
            Pin(num='CMD',name='CMD',func=pin_types.UNSPEC),
            Pin(num='VDD',name='VDD',func=pin_types.UNSPEC),
            Pin(num='GND',name='GND',func=pin_types.UNSPEC),
            Pin(num='CD',name='CD',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'SWD_1X6_PROGRAM_HEADER', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SWD_1X6_PROGRAM_HEADER'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'EasyEDA:SWD_1X6_PROGRAM_HEADER', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC),
            Pin(num='5',name='5',func=pin_types.UNSPEC),
            Pin(num='6',name='6',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'USB_FS_DFU_SERVICE_PORT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_FS_DFU_SERVICE_PORT'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'EasyEDA:USB_FS_DFU_SERVICE_PORT', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC),
            Pin(num='4',name='4',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'BOOT0_SELECT_JUMPER', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BOOT0_SELECT_JUMPER'}), 'ref_prefix':'JP', 'fplist':None, 'footprint':'EasyEDA:BOOT0_SELECT_JUMPER', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC),
            Pin(num='3',name='3',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'BOOT0_PULLDOWN_100K', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BOOT0_PULLDOWN_100K'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'EasyEDA:BOOT0_PULLDOWN_100K', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'NRST_PULLUP_10K', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NRST_PULLUP_10K'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'EasyEDA:NRST_PULLUP_10K', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'NRST_RESET_CAP_100NF', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NRST_RESET_CAP_100NF'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:NRST_RESET_CAP_100NF', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'TAXM8M4RDBCCT2T_HSE_8MHZ', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TAXM8M4RDBCCT2T_HSE_8MHZ'}), 'ref_prefix':'Y', 'fplist':None, 'footprint':'EasyEDA:TAXM8M4RDBCCT2T_HSE_8MHZ', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'HSE_LOAD_CAP_IN_18PF', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'HSE_LOAD_CAP_IN_18PF'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:HSE_LOAD_CAP_IN_18PF', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'HSE_LOAD_CAP_OUT_18PF', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'HSE_LOAD_CAP_OUT_18PF'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:HSE_LOAD_CAP_OUT_18PF', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'MCU_SDRAM_DECOUPLING_100NF_ARRAY_A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MCU_SDRAM_DECOUPLING_100NF_ARRAY_A'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:MCU_SDRAM_DECOUPLING_100NF_ARRAY_A', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] }),
        Part(**{ 'name':'LCD_TOUCH_DECOUPLING_100NF_ARRAY_B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LCD_TOUCH_DECOUPLING_100NF_ARRAY_B'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'EasyEDA:LCD_TOUCH_DECOUPLING_100NF_ARRAY_B', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.UNSPEC),
            Pin(num='2',name='2',func=pin_types.UNSPEC)] })])